### ISSUE TITLE
Using Spectrogram as an external meter

### ISSUE THREAD

**Issue by davidmantegna** [googlecreativelab/chrome-music-lab#10]
Hi! Your spectrogram is awesome, I've never seen such a helpful tool. 
I was asking myself if is there any chance to use it inside Chrome as an external meter to analyse the audio coming out of Ableton Live, or any other application reproducing audio.
At the moment I'm using other meters outside Live, routing it's output to them, such as Audiophile Spectre. For instance their spectrogram it's not brilliant as yours.
So, I hope you'll have any bright idea in mind to achieve this result.

**Comment by tambien** [comment]
I think the easier way to accomplish this would be to use an application like [Soundflower](https://soundflower.en.softonic.com/mac) or [Loopback](https://rogueamoeba.com/loopback/) to route the audio output from Live to the audio input of Chrome. Then the 'mic' button on Spectrogram would be listening to the output from Live. 

I haven't tried this myself, but i think it should work

**Comment by davidmantegna** [comment]
How do I set Chrome to receive the input from Loopback?

2017-08-01 17:37 GMT+02:00 Yotam Mann <notifications@github.com>:

**Comment by davidmantegna** [comment]
How can I set the audio input of Chrome? There's nothing similar to
Spectre's input in Chrome settings
