### ISSUE TITLE
Can I play more than two notes in Multiplayer?

### ISSUE THREAD

**Issue by jaehwang2** [googlecreativelab/chrome-music-lab#16]
I want to play C3 and C4 (like Song Maker)

PolySynth is possible to use  triggerAttackRelease like this
this._piano.triggerAttackRelease([Multiple Notes])

But I think MultiPlayer isn't possible to send Multiple Notes as a parameter

Can I make them play simultaneously?

**Comment by tambien** [comment]
Probably a question which should be directed to the [Tone.js](https://github.com/Tonejs/Tone.js) github or [forum](https://groups.google.com/forum/#!forum/tonejs).
