### ISSUE TITLE
Blankety blank

### ISSUE THREAD

**Issue by Ganesha2282882** [googlecreativelab/chrome-music-lab#28]
Blank page:
![image](https://user-images.githubusercontent.com/59745725/74366908-e4fa4580-4d9e-11ea-854c-8f8ed89592b6.png)

I don't know what is wrong.

**Comment by ccjmne** [comment]
It looks like one of your extensions is preventing the page from loading properly.

Try disabling uBlock Origin and I'm sure your experience will be quite different :)

**Comment by bobfart2395** [comment]
thank you so much it worked
