### ISSUE TITLE
Spectogram gulp build-all fails on linux, cause of file names case

### ISSUE THREAD

**Issue by romulka** [googlecreativelab/chrome-music-lab#3]
Error: module "./cameraController" not found from "/home/roman/projects/chrome-music-lab/spectrogram/src/javascripts/3D/visualizer.js"

it's called cameracontroller.js

Error: module "./ui/spectrogram" not found from "/home/roman/projects/chrome-music-lab/spectrogram/src/javascripts/fake_60d86ccf.js"

fodler called UI not ui.

**Comment by mrayinteractive** [comment]
Fixed in #12
