### ISSUE TITLE
Distribution 

### ISSUE THREAD

**Issue by kaanmutlu17** [googlecreativelab/chrome-music-lab#42]
Are the songs made here suitable for posting on social media?

**Comment by samir-patnaik** [comment]
Judging by the Apache 2.0 license, this project is released under, I'm sure you can safely share your songs on Social Media.

**Comment by kaanmutlu17** [comment]
> @kaanmutlu17
> Judging by the Apache 2.0 license, this project is released under, I'm sure you can safely share your songs on Social Media.

Thanks, I got Spotify music thanks to chrome lab.
