### ISSUE TITLE
Rhythm lab won't open on chromebook

### ISSUE THREAD

**Issue by velois129** [googlecreativelab/chrome-music-lab#43]
Hi, I can't use the rhythm lab on my chromebook.
I was told that if it doesn't work on mine, it won't either on my students.
Could you look into this?

**Comment by eperez84** [comment]
Hello,

Are you still experiencing this issue?  If so, can you please provide the following info:

- Chromebook model
- ChromeOS version

**Comment by eperez84** [comment]
Hello,

Are you still experiencing this issue? If so, can you please provide the following info:

- Chromebook model
- ChromeOS version

**Comment by velois129** [comment]
It works now.

*Ms. Lois H. Jang*
Choral director
Calhoun County High School
P: 803.655.4030
