### ISSUE TITLE
some apps does not run on ipad mini 5

### ISSUE THREAD

**Issue by magiwogg** [googlecreativelab/chrome-music-lab#45]
Hello.
As a music teacher, Chrome Music Lab helps me a lot in classes.
However, when I try to run on iPad mini 5 , some of the apps -Rhythm, Ossilators and most of thwm - does not work.
I tried multiple browsers- Chrome, Safari, Firefox, Sleipnir, Dolphin, etc, but it did not help.
Could someone help me out?

**Comment by Ivinish401** [comment]
We use this at my job too.  I can confirm updates do not change this and the settings and hardware can be identical and half the class will not work while the others do.  The ones that do not work can get on some and not the others. 

For the devs specifically, I did a quick look at the console from the iPad on safari and I looked only on the oscillators (this one is consistently a problem) and found that it is not recognizing two variables: OscillatorNode and af.  One more thing is the $sanitize function does not work if that is of any help.

**Comment by eperez84** [comment]
Hello,

What iOS version are your devices on?  Can you check again? I suspect that this is a duplicate of #46, for which a fix was recently rolled out

**Comment by eperez84** [comment]
What iOS version are your devices on? Can you check again? I suspect that this is a duplicate of #46, which may have been recently fixed

**Comment by magiwogg** [comment]
Also I have contacted development team some weeks ago, and they told me its fixed - yes, its fine now!
Though it has a glitchy issue on "Voice Spinner", which happens when touching recorded waveform and trying to do DJ style scratch - which end up not spinning, making glitchy sound like granular synth.
I have told dev team about it. Thanks for the support!
