### ISSUE TITLE
Some labs like "Rhythm" and "Arpeggios" won't load under IOS (Tested in Ipad Pro, Iphone)

### ISSUE THREAD

**Issue by jjimenezcox** [googlecreativelab/chrome-music-lab#46]
Some labs like "Rhythm" and "Arpeggios" won't load under IOS 
I've tested using the latest model Ipad Pro, Iphone with the latest IOS version as well.
Same results on both devices.

Thanks in advance.

**Comment by eperez84** [comment]
@jjimenezcox - Can you check again?  There was an issue with iOS14 that was recently fixed

**Comment by eperez84** [comment]
Can you check again? There was an issue specific to iOS14 that was recently fixed

**Comment by jjimenezcox** [comment]
Seems to be working now.

Thanks for the follow-up!!!

Sent from my iPhone

On Dec 4, 2020, at 12:09 PM, Erick Perez <notifications@github.com> wrote:

﻿

Can you check again? There was an issue specific to iOS14 that was recently fixed
