### ISSUE TITLE
No download option appearing.

### ISSUE THREAD

**Issue by Telgorr** [googlecreativelab/chrome-music-lab#52]
Im using a Lenovo Chromebook
on Google Chrome
Version Version 88.0.4324.186

**Comment by eperez84** [comment]
Is this in reference to the Song Maker experiment?  If so, are you tapping on Save using your finger or are you clicking on the button with the touchpad?

**Comment by Telgorr** [comment]
I just restarted it now its working thanks and I had to click it with touchpad twice after restarting

**Comment by eperez84** [comment]
Issue no longer occurs when tapping on the save button vs clicking on it.  Feel free to reopen this if it happens again!
