### ISSUE TITLE
Link to repo

### ISSUE THREAD

**Issue by alvarobyrne** [googlecreativelab/chrome-music-lab#6]
Hi
Why wouldn´t you have a link form the experiments web page to the repo?
Thanks in advance.

**Comment by dobon** [comment]
the public-facing chrome-music-lab site DOES link to this repo:
1) go to chrome music lab: https://musiclab.chromeexperiments.com/Experiments
2) go to an experiment (I am interested in the chords experiment): https://musiclab.chromeexperiments.com/Chords
3) click the (?) in the top-right corner to cause a modal overlay/window to appear: 
```
Chrome Music Lab:Chords

A basic chord is made up of three notes. Tap a note on the piano to play a chord starting on that note.
Built by Yotam Mann. Source code available here.
```
which links to https://github.com/googlecreativelab/chrome-music-lab/tree/master/chords

The other experiments I checked (and to be certain, I didn't check all of them) have the same sort of link to github, in the same place.

**Comment by alvarobyrne** [comment]
@dobon thanks
