### ISSUE TITLE
can i inform that the certificate has expired for the website?

### ISSUE THREAD

**Issue by bowlsoup** [googlecreativelab/chrome-music-lab#67]
or that's what i think, it just says not secure
![image_2023-06-05_132709202](https://github.com/googlecreativelab/chrome-music-lab/assets/135606311/f51b81b8-db90-4438-ac6d-4157ca4a38d7)

**Comment by bowlsoup** [comment]
or it's something else idk

**Comment by mrayinteractive** [comment]
this has been resolved, let us know if you run across any more issues
